name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pulp matplotlib pandas numpy python-dateutil
        
    - name: Download CBC Solver
      run: |
        # Create solver directory if it doesn't exist
        if (-not (Test-Path "solver")) {
            New-Item -ItemType Directory -Path "solver" -Force
        }
        Write-Host "Solver directory created/verified"
        
        # Download CBC solver directly from COIN-OR
        try {
            Write-Host "Downloading CBC solver from COIN-OR..."
            
            # Download CBC binary
            $url = "https://github.com/coin-or/Cbc/releases/download/releases%2F2.10.10/Cbc-releases.2.10.10-w64-msvc17-md.zip"
            $output = "cbc.zip"
            
            Write-Host "Downloading from: $url"
            Invoke-WebRequest -Uri $url -OutFile $output
            
            if (Test-Path $output) {
                Write-Host "Download successful. Extracting..."
                Expand-Archive -Path $output -DestinationPath "cbctemp" -Force
                
                # Find cbc.exe in the extracted files
                $cbcExe = Get-ChildItem -Path "cbctemp" -Recurse | Where-Object { $_.Name -eq 'cbc.exe' } | Select-Object -First 1
                
                if ($cbcExe) {
                    Write-Host "Found CBC executable at: $($cbcExe.FullName)"
                    Copy-Item -Path $cbcExe.FullName -Destination "solver/cbc.exe" -Force
                    
                    if (Test-Path "solver/cbc.exe") {
                        $fileSize = (Get-Item "solver/cbc.exe").Length
                        Write-Host "CBC solver copied successfully. Size: $fileSize bytes"
                    } else {
                        throw "Failed to copy CBC solver"
                    }
                } else {
                    throw "Could not find cbc.exe in extracted files"
                }
                
                # Clean up temporary files
                Remove-Item -Path $output -Force
                Remove-Item -Path "cbctemp" -Recurse -Force
            } else {
                throw "Download failed"
            }
        } catch {
            Write-Error "Failed to setup CBC solver: $_"
            exit 1
        }
        
    - name: Create PyInstaller spec file
      run: |
        @"
        # -*- mode: python ; coding: utf-8 -*-
        import os

        block_cipher = None

        # Get the absolute path to the solver directory
        solver_dir = os.path.abspath(os.path.join(SPECPATH, 'solver'))
        solver_binary = os.path.join(solver_dir, 'cbc.exe')

        print(f"Solver directory: {solver_dir}")
        print(f"Solver binary path: {solver_binary}")

        if not os.path.exists(solver_binary):
            raise Exception(f"CBC solver not found at {solver_binary}")

        a = Analysis(
            ['PS_GUI3.py'],
            pathex=[],
            binaries=[],
            datas=[
                (solver_binary, 'solver'),  # Place CBC solver in solver directory
                (os.path.dirname(solver_binary), 'solver'),  # Include entire solver directory
            ],
            hiddenimports=[
                'pandas', 'numpy', 'pulp', 'matplotlib', 'dateutil', 'dateutil.zoneinfo',
                'pulp.apis', 'pulp.apis.coin_api'  # Add PuLP solver-related imports
            ],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=[],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            [],
            exclude_binaries=True,
            name='Production Scheduler',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            console=True,
            disable_windowed_traceback=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
        )

        # This creates the directory with all binaries
        coll = COLLECT(
            exe,
            a.binaries,
            a.zipfiles,
            a.datas,
            strip=False,
            upx=True,
            upx_exclude=[],
            name='Production Scheduler'
        )
        "@ | Out-File -Encoding UTF8 Production_Scheduler.spec
        
    - name: Build with PyInstaller
      run: |
        pyinstaller Production_Scheduler.spec
        
    - name: Verify CBC solver in build
      run: |
        Write-Host "Checking for CBC solver in build..."
        
        # First, list only the root directory contents
        Write-Host "`nContents of dist root directory:"
        Get-ChildItem "dist" | ForEach-Object {
            Write-Host $_.FullName
        }
        
        # Then, list the Production Scheduler directory
        Write-Host "`nContents of Production Scheduler directory:"
        Get-ChildItem "dist/Production Scheduler" | ForEach-Object {
            Write-Host $_.FullName
        }
        
        # Check multiple possible locations for cbc.exe
        $possiblePaths = @(
            "dist/Production Scheduler/cbc.exe",
            "dist/Production Scheduler/_internal/cbc.exe",
            "dist/Production Scheduler/solver/cbc.exe"
        )
        
        $found = $false
        foreach ($path in $possiblePaths) {
            Write-Host "`nChecking path: $path"
            if (Test-Path $path) {
                $fileSize = (Get-Item $path).Length
                Write-Host "CBC solver found at: $path"
                Write-Host "Size: $fileSize bytes"
                $found = $true
                break
            }
        }
        
        if (-not $found) {
            Write-Host "`nSearching for cbc.exe in all subdirectories..."
            $cbcFiles = Get-ChildItem -Path "dist" -Recurse -Filter "cbc.exe"
            if ($cbcFiles) {
                Write-Host "Found CBC solver in unexpected location(s):"
                $cbcFiles | ForEach-Object {
                    Write-Host $_.FullName
                    Write-Host "Size: $($_.Length) bytes"
                }
                
                # Copy the first found CBC solver to the expected location
                $targetPath = "dist/Production Scheduler/cbc.exe"
                Copy-Item -Path $cbcFiles[0].FullName -Destination $targetPath -Force
                Write-Host "`nCopied CBC solver to: $targetPath"
            } else {
                Write-Error "CBC solver not found in any location"
                exit 1
            }
        }
        
    - name: Verify dateutil zoneinfo
      run: |
        Write-Host "Checking dateutil zoneinfo..."
        $zoneinfoPath = "dist/Production Scheduler/_internal/dateutil/zoneinfo"
        if (Test-Path "$zoneinfoPath/dateutil-zoneinfo.tar.gz") {
            $fileInfo = Get-Item "$zoneinfoPath/dateutil-zoneinfo.tar.gz"
            Write-Host "Zoneinfo file found. Size: $($fileInfo.Length) bytes"
            Write-Host "Last write time: $($fileInfo.LastWriteTime)"
            
            # Reset the timestamp to current time to avoid future dates
            $fileInfo.LastWriteTime = Get-Date
            Write-Host "Updated timestamp to: $($fileInfo.LastWriteTime)"
        } else {
            Write-Error "Dateutil zoneinfo file not found"
            exit 1
        }
        
    - name: Get timestamp for tag
      id: timestamp
      run: |
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        echo "::set-output name=value::$timestamp"
        
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}_${{ steps.timestamp.outputs.value }}
        release_name: Production Scheduler ${{ github.ref_name }} (Build ${{ steps.timestamp.outputs.value }})
        draft: false
        prerelease: false
        body: |
          Production Person Scheduler ${{ github.ref_name }}
          
          ### Build Information
          - Build Time: ${{ steps.timestamp.outputs.value }}
          - Version: ${{ github.ref_name }}
          
          ### Features
          - Production scheduling optimization
          - Multiple machine support
          - Staff allocation
          - Shift planning
          
          ### Installation
          1. Download and extract the zip file
          2. Run "Production Scheduler.exe" from the extracted folder
          
          ### Changes
          - Fixed PuLP solver integration
          - Improved stability and performance
          - Added console window for troubleshooting
          - Direct CBC solver download from COIN-OR
          - Modified solver bundling location
    
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path "dist/Production Scheduler" -DestinationPath "Production_Scheduler_${{ steps.timestamp.outputs.value }}.zip"
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Production_Scheduler_${{ steps.timestamp.outputs.value }}.zip
        asset_name: Production_Scheduler_${{ steps.timestamp.outputs.value }}.zip
        asset_content_type: application/zip